---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaojh.
--- DateTime: 2019/3/18 14:09
--- 配置抽取模块
---
local module = {};

local dataSave = {};

--- 获取快速搜索表格的名字，独立出来
local function getQuickTableName(fileName, sheetName, key)
    return "_table_" .. fileName .. "_" .. sheetName .. "_" .. key;
end

--- 获取表格的名字，独立出来
local function getTableName(fileName, sheetName)
    return "Data._table_" .. fileName .. "_" .. sheetName;
end

--- 在快速查询表中搜索数据
local function getDataInQuickTable(fileName, sheetName, key, value)
    local quickTable = dataSave[getQuickTableName(fileName, sheetName, key)];
    if (quickTable == nil) then
        return nil;
    end
    return quickTable[value];
end

--- 建立快速查询表
local function buildQuickSearchTable(fileName, sheetName, key)
    local dataTable = module.getTable(fileName, sheetName);
    if (dataTable == nil) then
        return ;
    end
    local quickTable = {};
    for _, v in pairs(dataTable) do
        if (v[key] ~= nil) then
            if (quickTable[v[key]] == nil) then
                quickTable[v[key]] = {};
            end
            quickTable[v[key]][#quickTable[v[key]] + 1] = v;
        end
    end
    dataSave[getQuickTableName(fileName, sheetName, key)] = quickTable;
end

--- 根据字段和value搜索数据
local function getDataByKey(fileName, sheetName, key, value)
    local returnTable = {};
    local table = module.getTable(fileName, sheetName);
    if (table == nil) then
        return nil;
    end
    for _, v in pairs(table) do
        if (v[key] == value) then
            returnTable[#returnTable + 1] = v;
        end
    end
    return returnTable;
end

--- 获取数据表格
module.getTable = function(fileName, sheetName)
    return require(getTableName(fileName, sheetName));
end

--- 更具主键值获取
module.getDataById = function(fileName, sheetName, id)
    local table = module.getTable(fileName, sheetName);
    --- 判断表格是不是为空
    if (table == nil) then
        return nil;
    end
    return table[id];
end

--- saveFlag 这个为true的时候会建立一个快速查询表，缓存在内存中，默认开启
--- 会返回一个table，个数是不一定的
module.getDataByKey = function(fileName, sheetName, key, value, saveFlag)
    local data = getDataInQuickTable(fileName, sheetName, key, value);
    if (data ~= nil) then
        return data;
    end
    if (saveFlag == false) then
        return getDataByKey(fileName, sheetName, key, value);
    else
        buildQuickSearchTable(fileName, sheetName, key);
        return getDataInQuickTable(fileName, sheetName, key, value);
    end
end

return module;