---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaojh.
--- DateTime: 2019/3/14 10:34
local logModule = require("Module.LogModule");
local table = {};

table[1] = 1;
table[2] = 2;
table[3] = nil;
table[4] = 3;

table = {1, 2, 3, nil, 4};


logModule.showLog(table);

logModule.showLog("123213");

logModule.showLog(nil);

logModule.showLog(12312.2);